### PR TITLE
bug fix for system vended mill, no `MILL_CLASSPATH` avalible.

### PR DESCRIPTION
**Pull request by sequencer**

### CODE REVIEW

**Comment by samvel1024** [comment]
Thanks a lot for the fix. I am only worried by the fact that it will not run on Windows. Maybe it's better to throw an exception with a detailed message.

**Comment by sequencer** [comment]
Emmm I didn’t use windows for development before. Maybe could you give a little help? :p

**Comment by samvel1024** [comment]
I also don't use windows, but using `which` will fail there for sure. First of all, I don't quite get the reason why you don't have `MILL_CLASSPATH` defined. Is it acceptable in the first place ?

**Comment by sequencer** [comment]
In the Arch Linux [PKGBUILD](https://www.archlinux.org/packages/community/any/mill/), we just `assembly` and package to `/usr/bin`, so no `MILL_CLASSPATH` here, what's your suggest to this case? I can PR some modifications to packager, but distribution certainly not like adding this `env` to `profile` as default.

**Comment by samvel1024** [comment]
OK to make sure that windows users can get some reasonable feedback we can add some message saying that `MILL_CLASSPATH` env var is not defined. Then we can try to run `which mill` to try to fix it, and if that one fails too, then we can ask the user to set it manually. This way it will be less confusing for a win user. Also this execution path should happen rarely, so I suppose it's an exceptional case anyway. Thanks for fixing this.

**Comment by sequencer** [comment]
I see, in the Arch Linux,
`mill` was wrapped by(generated directly by `mill -i all __.publishLocal assembly`) 
```sh
@ 2>/dev/null # 2>nul & echo off & goto BOF^M
:
if [ -z "$JAVA_HOME" ] ; then
  JAVACMD="java"
else
  JAVACMD="$JAVA_HOME/bin/java"
fi
case "$1" in
  -i | --interactive )
    exec $JAVACMD -DMILL_CLASSPATH=$0 -DMILL_VERSION=0.5.1-77-bf9171 -Djna.nosys=true $JAVA_OPTS -cp "$0" mill.MillMain "$@"
    ;;
  *)
    exec $JAVACMD -DMILL_CLASSPATH=$0 -DMILL_VERSION=0.5.1-77-bf9171 -Djna.nosys=true $JAVA_OPTS -cp "$0" mill.main.client.MillClientMain "$@"
    ;;
esac
exit
```
The `MILL_VERSION` and `MILL_CLASSPATH` is set by `java -Dxxx=xxx`, which means, we can access this env by `System.getProperty()` rather than `scala.sys.env.get`
Here is `amm` output:
```
@ scala.sys.env.get("MILL_VERSION")
res1: Option[String] = None

@ System.getProperty("MILL_VERSION")
res2: String = "0.5.1-77-bf9171"
```

So maybe we need @lihaoyi to ask which one is the expected behavior, `scala.sys.env.get` or `System.getProperty`?

**Comment by samvel1024** [comment]
Thanks for the information,  then I think it can be handled even in a simpler manner. Like `Option` chaining and throwing with a message if neither property nor env variable is set. Although I am not sure if this will cover all the corner cases.

**Pull request merged**
